### ISSUE TITLE
get_historical_data fail

### ISSUE THREAD

**Issue by skylyj** [JerBouma/FinanceToolkit#79]
Here is my code.
```
companies = Toolkit(["MSFT"], api_key=API_KEY, start_date="2020-12-31", quarterly=True)
historical_data = companies.get_historical_data()
```
It failed with the following error displayed.
```
Obtaining historical data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.20it/s]
Exception in thread Thread-120 (worker):
Traceback (most recent call last):
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/site-packages/financetoolkit/historical_model.py", line 95, in worker
    historical_data = get_historical_data_from_financial_modeling_prep(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/site-packages/financetoolkit/historical_model.py", line 329, in get_historical_data_from_financial_modeling_prep
    dividends_df.index = pd.to_datetime(dividends_df.index)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 1121, in to_datetime
    result = convert_listlike(arg, format, name=arg.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 488, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tommy/miniforge3/envs/jupyter-ai/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 519, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 534, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 355, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "2023-08-16" doesn't match format "%Y-%b-%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

**Comment by skylyj** [comment]
oops! I restarted jupyter kernel, this problem disappeared.
